### PR TITLE
Made instructions more newbie-friendly

### PR DESCRIPTION
**Pull request by john-azariah-cba**
Added arguments to expose ports to each docker run
Set the advertised.host.name environment variable correctly to ensure the producer and consumer talk to each other
Added sample docker.ps output to help troubleshooting

### CODE REVIEW

**Comment by john-azariah-cba** [comment]
[clabot:check]

From: Confluent CLA Bot
Reply-To: confluentinc/docker-images
Date: Wednesday, 3 June 2015 10:59 am
To: confluentinc/docker-images
Cc: John Azariah
Subject: Re: [docker-images] Made instructions more newbie-friendly (#1)

 [clabot:check]

************** IMPORTANT MESSAGE *****************************       
This e-mail message is intended only for the addressee(s) and contains information which may be
confidential. 
If you are not the intended recipient please advise the sender by return email, do not use or
disclose the contents, and delete the message and any attachments from your system. Unless
specifically indicated, this email does not constitute formal advice or commitment by the sender
or the Commonwealth Bank of Australia (ABN 48 123 123 124) or its subsidiaries. 
We can be contacted through our web site: commbank.com.au. 
If you no longer wish to receive commercial electronic messages from us, please reply to this
e-mail by typing Unsubscribe in the subject line. 
**************************************************************

**Comment by ewencp** [comment]
@john-azariah-cba Thanks for the patch. I think adding the -p flags makes a lot of sense since docker users will probably already know what these mean and know whether they need them.

On the DOCKER_MACHINE and advertised host portion -- these really only work if you're using boot2docker. Might make more sense to use remove the --env flag, then put a follow up version with the flag in a comment immediately following it, noting you'll need the flag if using boot2docker.

Also, schema registry and kafka-rest (the latter which admittedly is not in that quickstart) also have similar settings called `host.name`, but I don't think those can currently be set with a --env with the current images. They probably require config changes.

**Comment by realflash** [comment]
Confused newbie here. Thankyou to the author of #1 which enabled me to get started. 

I used this first line instead:
```
DOCKER_MACHINE=`ifconfig docker0 | awk '/inet addr/ {print $2}' | awk -F ':' '{print $2}'`
```
It just gets the IPv4 address of the interface docker0. Perhaps @ewencp can just make the changes he suggests because as is the instructions aren't usable.

**Comment by ewencp** [comment]
@john-azariah-cba Thanks for the patch, I had to adapt it a bit to get it up to date with some other changes, but your authorship is maintained here: bffaaae324562f8dbc3cfb02827ccffa3a884a1e. I updated things a bit to try to clarify how it should work with stock Docker on Linux and boot2docker on Mac + Windows.

@realflash Not sure why you needed to use that alternative command. boot2docker's ip subcommand should give you the address of the `docker0` interface...

**Pull request closed without merging**
