### PR TITLE
fix docker-compose

### PR DESCRIPTION
**Pull request by afolarin**
This updated docker-compose.yml file addresses issue #24 to set-up running on single node without breaking out of containers network namespace (net=host). 

Environment variables could be separated into env-files.

### CODE REVIEW

**Comment by jonathanperret** [comment]
Hi! Not a committer here but I do use these images with docker-compose, so I thought I'd pitch in. I think it's a great idea to improve that `docker-compose.yml`, but in my opinion there are a couple issues with this version.

`links` the way they are configured here (`kafka:kafka`) do not buy anything over `depends_on` since all containers in the composition are visible to each other in the networking model implied by the v2 file format (https://docs.docker.com/compose/compose-file/).

`KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181` and `KAFKA_ADVERTISED_PORT=9092` are the default values so one might as well leave them out. Likewise for `RP_ZOOKEEPER_CONNECT=zookeeper:2181`. Possibly others as well, but these I can attest may be removed. Might serve as documentation though.

Those are very minor. The next one though is critical: `KAFKA_ADVERTISED_HOST_NAME` is hardcoded to `10.200.100.171`.

I don't know of an ideal option for that `KAFKA_ADVERTISED_HOST_NAME`, but setting it to `kafka` (one has to be explicit here because the container's `hostname` will be a random hex number, even though the name `kafka` will resolve to that container inside the composition's network) is a good start as it lets the Kafka composer as well as any other in the composition refer to it under its advertised hostname.

The problems (that likely led to the `net=host` recommendation, btw) begin when you want to access Kafka from outside Docker (by the way, if you don't, all those port forwardings should definitely go away).

Because a Kafka broker advertises a host name that the client must be able to resolve in the same way as the broker itself, you'd have to make it so that `kafka` on your client machine resolves to your Docker host's IP. I do this by editing `/etc/hosts` as described in https://github.com/confluentinc/docker-images#local-host-entries — that's the non-ideal part.

For completeness, note that even on Linux where Docker exposes ports on `localhost`, setting `KAFKA_ADVERTISED_HOST_NAME` to `localhost` will only work partially because as soon as a container tries to connect to the broker (if you were to add a second broker to the composition, for example), it will instead connect back to itself and all hell will break loose.

I hope this helps.

**Comment by afolarin** [comment]
@jonathanperret -- very helpful thanks!

on `links` front:
I guess, unless you need to alias then it should be sufficient to use the `depends_on`

default ports:
I take your point, one probably doesn't need to define the defaults in more than one place. 

on the hardcoded IP / net=hosts:
I wondered about this (mostly from here https://hub.docker.com/r/wurstmeister/kafka/) though I had intended a place-holder for the IP to be substituted. 

I thought `KAFKA_ADVERTISED_HOST_NAME` was purely for external client use, with on the composition's network service name `kafka`. So if I understand correctly, using `KAFKA_ADVERTISED_HOST_NAME=kafka` then on each external client `/etc/hosts` resolve `kafka` to the docker host IP. So with the port forwarding setup, as long as the external clients can resolve "in a none-ideal way" then net=hosts is not needed?

**Comment by jcustenborder** [comment]
@afolarin Thanks for the pull request! The main reason we use net:host is the advertised hostname problem coming across from the hosting machine to the docker image. `advertised.host.name` is no longer used and should be replaced with `advertised.listeners`

Have you taken a look at the [docker-compose](https://github.com/confluentinc/docker-images#docker-compose) section of the [README.MD](https://github.com/confluentinc/docker-images#docker-compose)? It's a similar workaround but we have you create a hosts entry for confluent in your /etc/hosts file.

**Comment by andrewegel** [comment]
Causing CI to break due to the "unknown repository" - This needs to be closed to get around that. If this change is still required, please re-do it.

**Pull request closed without merging**
